### ISSUE TITLE
DCQ interferes with custom filtering

### ISSUE THREAD

**Issue by tommm** [hidakatsuya/redmine_default_custom_query#10]
I don't know whether this is something you'll want to look into but I'm using your default custom query (DCQ) plugin with Planio (http://plan.io) that uses a custom CRM plugin.

It provides a link to search for issues that involve a customer, from the link _issues?company_cache=[company name]&set_filter=1_. The problem is that DCQ seems to override this and shows the default query and not filtering by customer.

Is this something that can be fixed?

Cheers,
Tom

**Comment by hidakatsuya** [comment]
@tommm I probably think that you can solve the problem by adding `without_default=1` parameter to the link, like `issues?company_cache=[company name]&set_filter=1&without_default=1`.

**Comment by tommm** [comment]
@hidakatsuya that works perfectly. I've let Planio know. Thanks for the feedback (and the awesome plugin!).

**Comment by hidakatsuya** [comment]
@tommm :smile:
