### ISSUE TITLE
Can Not Create Query

### ISSUE THREAD

**Issue by ElskerDane** [hidakatsuya/redmine_default_custom_query#15]
My System:
Rails 4.2
Ruby 1.9
Redmine 3.0.3
Windows 7 64bit

I recently installed your plugin but I cannot find out how to make it work.  Here are some images of what I am seeing:
![queryexample1](https://cloud.githubusercontent.com/assets/12851016/8478143/71187dea-209d-11e5-84a0-8459eb567c3c.PNG)
![queryexample2](https://cloud.githubusercontent.com/assets/12851016/8478152/77abb06e-209d-11e5-9817-5e9b2442a3a3.PNG)
![queryexample3](https://cloud.githubusercontent.com/assets/12851016/8478154/7a9cf134-209d-11e5-8b1d-bce2b90dcad0.PNG)

Do you know where I have to go to create a query?  I would think there would be a "create query" button somewhere but I cannot get it to work...

**Comment by hidakatsuya** [comment]
Please see http://www.redmine.org/projects/redmine/wiki/RedmineIssueList#Custom-queries. In addition, a public/global query can be set as default query.

**Comment by hidakatsuya** [comment]
@ElskerDane I'd like you to post your questions from [here](https://gitter.im/hidakatsuya/redmine_default_custom_query?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge) next time.

**Comment by ElskerDane** [comment]
Thank you very much for your help!
