### ISSUE TITLE
Problem in Issue summary page

### ISSUE THREAD

**Issue by atopcu** [hidakatsuya/redmine_default_custom_query#18]
Hi,
When a default custom query active in a project, The Issue filter links doesn't work on [Issue] Summary page, You are seen always default query result in issue list.

Environment:
  Redmine version                3.1.2.stable.14882
  Ruby version                   2.0.0-p481 (2014-05-08) [x86_64-linux]
  Rails version                  4.2.4
  Environment                    production
  Database adapter               Mysql2

There is no error message on the GUI.

Regards.

**Comment by maeda-m** [comment]
Thank you for your report.
It was resolved with #32 .
