### ISSUE TITLE
Can't open "setting" tab

### ISSUE THREAD

**Issue by ryoji-takeuchi** [hidakatsuya/redmine_default_custom_query#42]
After install redmine_default_custom_query, when open setting tab of a project, **setting tab never open** so redmine_default_custom_query function also can't set.
**Redmine version is 4.0.4**
Other plugin : **DMSF, Lychee basic, Lychee gantt chart**

**Comment by maeda-m** [comment]
Please refer to #37 .

**Comment by ryoji-takeuchi** [comment]
I read again DMSF release note. Regarding important notice, alias_method_chain is not changed after DMSF 1.6.1 and still exist latest version 2.4.1 right? That's why Maeda-san wrote "please refer to #37. 
But I also read some report that DMSF and Default custom query work together. 
I also read project #43 but Maeda-san don't want to close the issue with patch by picman-san. I little confused.

**Comment by maeda-m** [comment]
Thank you for the report.
Released [version 1.5.0](https://github.com/hidakatsuya/redmine_default_custom_query/releases/tag/1.5.0) !

**Comment by ryoji-takeuchi** [comment]
Plugin can be installed and can open setting tab with 1.5.0. 
Thank you for your update and hard work !
