### ISSUE TITLE
Can't open "setting" tab

### ISSUE THREAD

**Issue by ryoji-takeuchi** [hidakatsuya/redmine_default_custom_query#44]
Other situation from #42 
**Issue Condition**
Project setting tab can't open after redmine default custom query install
**Default custom query version**
1.4.0
**Redmine version**
4.0.4
**Other plugin**
Lychee basic and others (Lychee Project Template plugin 1.2.12)
Lychee gantt chart 4.1.6
Redmine Issue Templates plugin 0.3.5
Redmine Wiki Lists plugin 0.0.9

**This time DMSF is not installed. So, #37 (#1020 of DMSF) is not affected of this issue.**

**Condition Log**
Completed 200 OK in 533ms (Views: 198.5ms | ActiveRecord: 163.3ms)
Started GET "/projects/redmine4-0/settings" for 10.51.***.*** at 2019-10-21 08:37:20 +0900
Processing by ProjectsController#settings as HTML
  Parameters: {"id"=>"redmine4-0"}
  Current user: ****** (id=***)
  Rendering projects/settings.html.erb within layouts/base

**It looks server does not respond when setting tub is selected.**

**Comment by maeda-m** [comment]
Thank you for the report.
Released [version 1.5.0](https://github.com/hidakatsuya/redmine_default_custom_query/releases/tag/1.5.0) !

**Comment by ryoji-takeuchi** [comment]
Plugin can be installed and can open setting tab with 1.5.0. 
Thank you for your update and hard work !
