### ISSUE TITLE
Default custom query doesn't work

### ISSUE THREAD

**Issue by vshunkov** [hidakatsuya/redmine_default_custom_query#9]
Dear Katsuya HIDAKA,

I've just installed your plugin and found that it doesn't work on my side :(. I enabled it in project, created custom query and I cannot select it in plugin settings, drop-down list is empty.
Redmine version 2.6.1
Ruby version 1.9.3-p194 (2012-04-20)

Regards,
Vladimir.

**Comment by hidakatsuya** [comment]
@vshunkov Visibility of the query is set to public? Visibility of the query must be set to public.

**Comment by vshunkov** [comment]
That was a reason. Issue solved. Thank you!

**Comment by hidakatsuya** [comment]
@vshunkov :smile:

**Comment by at-tantv** [comment]
How to set Visibility of the query must be set to public ?
Thank you
